CREATE TABLE discovery_tasks (
    id                  BIGINT          NOT NULL AUTO_INCREMENT,
    task_type           VARCHAR(32)     NOT NULL,
    status              VARCHAR(32)     NOT NULL DEFAULT 'PENDING',
    preset              VARCHAR(32)     NOT NULL DEFAULT 'FULL_DISCOVERY',
    target_scope        VARCHAR(512)    NOT NULL,
    ports               TEXT,
    timeout_millis      INT             NOT NULL DEFAULT 2000,
    sniff_duration_sec  INT             NOT NULL DEFAULT 60,
    network_interface   VARCHAR(64),
    summary             TEXT,
    error_message       TEXT,
    discovered_count    INT             NOT NULL DEFAULT 0,
    started_at          DATETIME(6),
    finished_at         DATETIME(6),
    created_at          DATETIME(6)     NOT NULL,
    updated_at          DATETIME(6)     NOT NULL,
    PRIMARY KEY (id),
    KEY idx_dt_status (status),
    KEY idx_dt_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE discovery_results (
    id                      BIGINT          NOT NULL AUTO_INCREMENT,
    task_id                 BIGINT          NOT NULL,
    ip                      VARCHAR(64)     NOT NULL,
    mac                     VARCHAR(32),
    hostname                VARCHAR(255),
    vendor_hint             VARCHAR(255),
    open_ports              TEXT,
    protocols               VARCHAR(512),
    device_type_candidate   VARCHAR(64),
    confidence              DECIMAL(4,3)    NOT NULL DEFAULT 0.000,
    source_type             VARCHAR(32)     NOT NULL DEFAULT 'SCAN',
    raw_evidence            TEXT,
    first_seen_at           DATETIME(6)     NOT NULL,
    last_seen_at            DATETIME(6)     NOT NULL,
    linked_asset_id         BIGINT,
    managed                 TINYINT(1)      NOT NULL DEFAULT 0,
    created_at              DATETIME(6)     NOT NULL,
    updated_at              DATETIME(6)     NOT NULL,
    PRIMARY KEY (id),
    KEY idx_dr_task_id (task_id),
    KEY idx_dr_ip (ip),
    KEY idx_dr_managed (managed)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
